---
- name: prompt username
  ansible.builtin.pause:
    prompt: "Enter datasette username"
  register: username_prompt
  when: datasette_username is falsy

- name: set username
  ansible.builtin.set_fact:
    datasette_username: "{{ username_prompt.user_input }}"
  when: datasette_username is falsy

- name: prompt user for password if not already set or passed as CLI arg
  ansible.builtin.pause:
    prompt: "Enter datasette password"
    echo: false
  register: password_prompt
  when: datasette_user_password is falsy

- name: set datasette_user_password to password from prompt
  ansible.builtin.set_fact:
    datasette_user_password: "{{ password_prompt.user_input }}"
  no_log: true
  when: datasette_user_password is falsy
